#
FROM camhd_motion_analysis_rq_worker_base:latest
MAINTAINER Aaron Marburg <amarburg@apl.washington.edu>


ADD . /code/camhd_motion_analysis
WORKDIR /code/camhd_motion_analysis

## Initial conan configuration
RUN conan config set settings_defaults.compiler.libcxx=libstdc++11

ENV BUILD_DIR docker-Release
ENV VERBOSE 1

RUN rake release:build

WORKDIR docker-Release
RUN make install
RUN ldconfig   ## Weird that i need to run this...

ENTRYPOINT ["/code/camhd_motion_analysis/python/rq_worker.py"]
