#
FROM camhd_motion_analysis_rq_worker_base:latest
MAINTAINER Aaron Marburg <amarburg@apl.washington.edu>

WORKDIR /code
RUN git clone https://github.com/CamHD-Analysis/camhd_motion_analysis.git

WORKDIR /code/camhd_motion_analysis

## Initial conan configuration
RUN conan config set settings_defaults.compiler.libcxx=libstdc++11

ENV BUILD_DIR docker-Release
ENV VERBOSE 1

RUN rake release:build

WORKDIR docker-Release
RUN make install && make clean
RUN ldconfig

ENTRYPOINT ["/code/camhd_motion_analysis/python/rq_worker.py"]
