version: '2'
volumes:
  camhd-minio:
    driver_opts:
      export: /mnt/zvol1/projects/camhd/dev/minio
      host: nas.san.apl.washington.edu
    driver: rancher-nfs
  camhd-dot-minio:
    driver_opts:
      export: /mnt/zvol1/projects/camhd/dev/dot-minio
      host: nas.san.apl.washington.edu
    driver: rancher-nfs

secrets:
  camhd-minio-secret-key:
    external: 'true'

services:

  lazycache:
    image: amarburg/go-lazycache:latest
    environment:
      LAZYCACHE_ALLOW_RAW_OUTPUT: 'true'
    labels:
      io.rancher.scheduler.affinity:host_label: labor=true
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'

  camhd-worker:
    image: amarburg/camhd-worker:${ENVIRONMENT}
    labels:
      io.rancher.scheduler.affinity:host_label: labor=true
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'

  minio:
    image: minio/minio:latest
    stdin_open: true
    volumes:
    - camhd-minio:/data
    - camhd-dot-minio:/root/.minio
    environment:
      MINIO_ACCESS_KEY: 'camhd'
      MINIO_SECRET_KEY_FILE: '/run/secrets/camhd-minio-secret-key'
    tty: true
    command: ["server", "/data"]
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_soft: in314=true


  rabbitmq:
    image: bitnami/rabbitmq:latest
    labels:
      io.rancher.container.pull_image: always

  camhd-injector:
    image: amarburg/camhd-worker:${ENVIRONMENT}
    environment:
      OUTPUT_DIR: s3://minio:9000/camhd-motion-metadata/
    stdin_open: true
    entrypoint: "python3"
    tty: true
    command: ["/code/camhd-motion-analysis/python/apps/recent_injector.py", "--days", "1", "--log", "INFO", "--threads", "16"]
    labels:
      io.rancher.scheduler.affinity:host_label: labor=true
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
      cron.schedule: 0 0 1 * * ?

  flower:
    image: amarburg/camhd-worker:${ENVIRONMENT}
    environment:
      CELERY_BROKER: amqp://user:bitnami@rabbitmq/
    stdin_open: true
    command: ["make", "flower"]
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: labor=true
