

namespace :prod do

  task :up do
    sh "ENVIRONMENT=latest rancher --debug up --stack camhd-analysis-prod -d --upgrade --prune"
  end

end


namespace :dev do

  task :up do
    sh "ENVIRONMENT=test rancher --debug up --stack camhd-analysis-dev -d --upgrade --prune"
  end

end
