version: '2'
services:

  lazycache:
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000

  camhd-worker:
    start_on_create: true

  rabbitmq:
    scale: 1
    start_on_create: true

  minio:
    scale: 1
    start_on_create: true

  camhd-injector:
    scale: 1
    start_on_create: true

  flower:
    scale: 1
    start_on_create: true
