pipeline:
  ## Build a test docker image
  build_docker:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t amarburg/camhd-worker-base --file deploy/Dockerfile_base .
      - docker build -t amarburg/camhd-worker:latest -t amarburg/camhd-worker:${DRONE_REPO_OWNER}-latest -t amarburg/camhd-worker:${DRONE_REPO_OWNER}-${DRONE_COMMIT_SHA} --file deploy/Dockerfile_prod .

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status:
        - success
        - failure
