#
# docker-compose runs a local one-worker cluster.   Good for testing
#
version: '3'
services:
  lazycache:
    image: amarburg/camhd_cache:latest
    environment:
      LAZYCACHE_ALLOW_RAW_OUTPUT: 'true'

  rabbitmq:
    image: bitnami/rabbitmq:latest
    environment:
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: bitnami

  ## Build local version for testing
  camhd-worker:
    build:
      context: ./
      dockerfile: deploy/Dockerfile_test
    depends_on:
      - rabbitmq
      - minio
      - lazycache
    environment:
      # Long delay, rabbitmq can be slow to start
      DELAY_START:  30

  minio:
    image: minio/minio
    volumes:
      - ..:/data
    command: ["server", "/data"]
    ports:
      - "9200:9000"
    environment:
      MINIO_ACCESS_KEY: camhd
      MINIO_SECRET_KEY: camhdcamhd
