FROM amarburg/camhd-worker-base:latest
MAINTAINER Aaron Marburg <amarburg@apl.washington.edu>

WORKDIR /code
RUN git clone https://github.com/CamHD-Analysis/camhd-motion-analysis.git

WORKDIR /code/camhd-motion-analysis

RUN git submodule init && git submodule update

ENV VERBOSE 1

RUN ./fips set config linux-make-release
RUN ./fips build

VOLUME /output/CamHD_motion_metadata

ADD docker/launch_worker.sh  /code/
ENTRYPOINT ["/code/launch_worker.sh"]
