FROM ubuntu:xenial
MAINTAINER Aaron Marburg <amarburg@apl.washington.edu>

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

RUN apt-get update && apt-get install --no-install-recommends --yes \
          libcurlpp-dev libcurl4-openssl-dev \
          libopencv-dev rake g++ cmake git \
          libboost-filesystem-dev libeigen3-dev libceres-dev \
          bzip2 ca-certificates libtclap-dev \
          libglib2.0-0 libxext6 libsm6 libxrender1 \
          mercurial subversion wget && \
    rm -rf /var/lib/apt/lists/*

## Use miniconda instead of system
RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    /bin/bash /tmp/miniconda.sh -b -p /opt/conda && \
    rm /tmp/miniconda.sh
ENV PATH /opt/conda/bin:$PATH

## Install packages from conda
RUN conda install python=3.6 setuptools wheel pillow numpy dask cytoolz cython

## .. and the remainder from pip (after upgrading pip)
RUN pip install --upgrade pip
RUN pip install py-cpuinfo minio celery flower

## Resolve a bug in the current xenial (and yakkety?) package for Ceres
RUN touch /usr/include/ceres/internal/config.h

## Resolve a bug in the current xenial (and yakkety?) package for curlpp
RUN sed -i s/std::string\(\\\([a-zA-Z\ \\\"]*\\\)\)/\\\1/ /usr/include/curlpp/Option.inl

## Install pycamhd
WORKDIR /code
RUN git clone https://github.com/CamHD-Analysis/pycamhd-lazycache.git

WORKDIR /code/pycamhd-lazycache
RUN pip install .
