FROM amarburg/camhd-worker-base:latest
MAINTAINER Aaron Marburg <amarburg@apl.washington.edu>

WORKDIR /code
RUN git clone https://github.com/CamHD-Analysis/camhd-motion-analysis.git

WORKDIR /code/camhd-motion-analysis

RUN ./fips set config linux-make-release
RUN ./fips build

WORKDIR /code/camhd-motion-analysis/python
RUN ls -al
RUN pip install -e .

ADD deploy/launch_worker.sh  /code/
ENTRYPOINT ["/code/launch_worker.sh"]
