FROM amarburg/camhd-worker-base:latest
MAINTAINER Aaron Marburg <amarburg@apl.washington.edu>

ADD . /code/camhd-motion-analysis
WORKDIR /code/camhd-motion-analysis

ENV VERBOSE 1
RUN ./fips set config linux-make-unittest
RUN ./fips build

WORKDIR /code/camhd-motion-analysis/python
RUN pip install -e .

VOLUME /output/CamHD_motion_metadata

ADD deploy/launch_worker.sh  /code
ENTRYPOINT ["/code/launch_worker.sh"]
